import React from 'react';
import {AbsoluteFill, Audio, Img, Sequence, interpolate, random, spring, useCurrentFrame, useVideoConfig} from 'remotion';
import {loadFont as loadOutfit} from '@remotion/google-fonts/Outfit';
import {WeddingProps, sectionPlan} from './types';
import {Rise, SceneFade} from './TemplateMotion';

const {fontFamily: font} = loadOutfit();
const colors = ['#FF5A7A', '#FFD447', '#42C6D7', '#7454D8', '#FF8E3C'];

const PartyBackground: React.FC = () => { const frame = useCurrentFrame(); return <AbsoluteFill style={{overflow: 'hidden', background: 'linear-gradient(155deg, #FFF6D8 0%, #FFE0EB 50%, #DDF8FF 100%)'}}>{Array.from({length: 52}).map((_, i) => { const w = 8 + random(`cp-w-${i}`) * 18; const x = random(`cp-x-${i}`) * 1080; const speed = 2 + random(`cp-s-${i}`) * 5; const y = (random(`cp-y-${i}`) * 2100 + frame * speed) % 2100 - 100; return <div key={i} style={{position: 'absolute', left: x, top: y, width: w, height: w * .45, borderRadius: i % 3 === 0 ? 50 : 3, background: colors[i % colors.length], transform: `rotate(${frame * (1 + i % 4) + i * 19}deg)`, opacity: .8}} />})}</AbsoluteFill>; };

const Balloon: React.FC<{left: number; top: number; color: string; delay: number}> = ({left, top, color, delay}) => { const frame = useCurrentFrame(); return <div style={{position: 'absolute', left, top: top + Math.sin((frame + delay) * .05) * 18, width: 145, height: 180, borderRadius: '50% 50% 48% 48%', background: color, boxShadow: 'inset -18px -16px 0 rgba(0,0,0,.08), inset 22px 15px 0 rgba(255,255,255,.22)'}}><div style={{position: 'absolute', left: 70, top: 180, height: 260, width: 2, background: 'rgba(50,50,50,.3)'}} /></div>; };

const Hero: React.FC<WeddingProps> = (props) => { const frame = useCurrentFrame(); const {fps} = useVideoConfig(); const pop = spring({frame, fps, config: {damping: 9, stiffness: 115}}); return <AbsoluteFill style={{justifyContent: 'center', alignItems: 'center', textAlign: 'center', padding: 90, fontFamily: font}}><Balloon left={55} top={210} color={colors[0]} delay={0} /><Balloon left={865} top={300} color={colors[2]} delay={18} /><Balloon left={760} top={1300} color={colors[3]} delay={36} /><Rise style={{fontSize: 31, fontWeight: 800, letterSpacing: 8, color: '#7454D8', textTransform: 'uppercase'}}>You’re invited to</Rise><div style={{fontSize: 265, fontWeight: 900, lineHeight: .9, color: '#FF5A7A', transform: `scale(${pop})`, textShadow: '9px 10px 0 #FFD447', margin: '50px 0 25px'}}>PARTY!</div><Rise delay={15} style={{fontSize: 94, fontWeight: 900, color: '#222'}}>{props.couple.partnerOne}</Rise><Rise delay={25} style={{fontSize: 37, fontWeight: 700, color: '#7454D8', marginTop: 45}}>{props.eventDate || 'Save the date'}<div style={{color: '#E34368', marginTop: 12}}>{props.venue.name}{props.venue.city ? ` · ${props.venue.city}` : ''}</div></Rise></AbsoluteFill>; };

const Message: React.FC<WeddingProps> = (props) => <AbsoluteFill style={{justifyContent: 'center', padding: 100, fontFamily: font, textAlign: 'center'}}><Rise style={{background: 'rgba(255,255,255,.88)', borderRadius: 70, padding: '100px 70px', boxShadow: '18px 20px 0 rgba(116,84,216,.2)', border: '5px solid #FFD447'}}><div style={{fontSize: 34, fontWeight: 900, color: '#FF5A7A', letterSpacing: 8, textTransform: 'uppercase'}}>Cake · music · memories</div><div style={{fontSize: 64, fontWeight: 800, color: '#24213A', lineHeight: 1.3, marginTop: 55}}>{props.message || 'Come celebrate an amazing year and make the next one unforgettable!'}</div><div style={{fontSize: 30, color: '#7454D8', fontWeight: 700, marginTop: 55}}>Hosted with love by {props.couple.partnerTwo}</div></Rise></AbsoluteFill>;

const Photo: React.FC<WeddingProps & {duration: number}> = (props) => { const frame = useCurrentFrame(); const photos = props.photos || []; return <AbsoluteFill style={{justifyContent: 'center', alignItems: 'center', fontFamily: font}}>{photos.length ? <div style={{position: 'relative', width: 820, height: 1180}}>{photos.slice(0, 3).map((src, i) => <div key={src} style={{position: 'absolute', inset: 0, padding: 22, background: '#FFF', boxShadow: '0 25px 70px rgba(70,40,80,.22)', transform: `rotate(${[-7, 6, -2][i]}deg) translate(${i * 13}px, ${i * 12}px) scale(${interpolate(frame, [0, props.duration], [1.04, 1])})`, opacity: i === Math.min(2, Math.floor(frame / Math.max(1, props.duration / Math.min(3, photos.length)))) ? 1 : .28}}><Img src={src} pauseWhenLoading style={{width: '100%', height: '100%', objectFit: 'cover'}} /></div>)}</div> : <div style={{fontSize: 260, fontWeight: 900, color: '#FF5A7A', textShadow: '10px 10px #FFD447'}}>HAPPY!</div>}</AbsoluteFill>; };

const Details: React.FC<WeddingProps> = (props) => <AbsoluteFill style={{justifyContent: 'center', padding: 105, fontFamily: font}}><Rise style={{fontSize: 85, fontWeight: 900, color: '#24213A', marginBottom: 55}}>Party Plan</Rise>{(props.schedule?.length ? props.schedule : [{name: 'Birthday Party', time: props.eventDate || 'Save the date'}]).slice(0, 4).map((item, i) => <Rise key={`${item.name}-${i}`} delay={i * 7} style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '32px 36px', margin: '16px 0', borderRadius: 28, background: colors[i % colors.length], color: i === 1 ? '#24213A' : '#FFF', fontSize: 37, fontWeight: 900, boxShadow: '8px 9px 0 rgba(40,30,50,.12)'}}><span>{item.name}</span><span style={{fontSize: 30}}>{item.time}</span></Rise>)}</AbsoluteFill>;

export const ConfettiPop: React.FC<WeddingProps> = (props) => { const {durationInFrames, fps} = useVideoConfig(); const frame = useCurrentFrame(); const p = sectionPlan(durationInFrames); const volume = interpolate(frame, [0, fps, durationInFrames - fps, durationInFrames], [0, 1, 1, 0], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'}); return <AbsoluteFill>{props.musicUrl ? <Audio src={props.musicUrl} volume={volume} /> : null}<PartyBackground /><Sequence durationInFrames={p.intro}><SceneFade duration={p.intro}><Hero {...props} /></SceneFade></Sequence><Sequence from={p.intro} durationInFrames={p.message}><SceneFade duration={p.message}><Message {...props} /></SceneFade></Sequence><Sequence from={p.intro + p.message} durationInFrames={p.photos}><SceneFade duration={p.photos}><Photo {...props} duration={p.photos} /></SceneFade></Sequence><Sequence from={p.intro + p.message + p.photos} durationInFrames={p.schedule}><SceneFade duration={p.schedule}><Details {...props} /></SceneFade></Sequence><Sequence from={durationInFrames - p.finale} durationInFrames={p.finale}><SceneFade duration={p.finale}><Hero {...props} /></SceneFade></Sequence></AbsoluteFill>; };
