import React from 'react';
import {AbsoluteFill, Audio, Img, Sequence, interpolate, random, spring, useCurrentFrame, useVideoConfig} from 'remotion';
import {loadFont as loadCormorant} from '@remotion/google-fonts/CormorantGaramond';
import {loadFont as loadOutfit} from '@remotion/google-fonts/Outfit';
import {WeddingProps, sectionPlan} from './types';
import {Rise, SceneFade} from './TemplateMotion';

const {fontFamily: serif} = loadCormorant();
const {fontFamily: sans} = loadOutfit();
const C = {black: '#111111', gold: '#D5B36A', blush: '#F7E9DC', white: '#FFFFFF'};

const Background: React.FC = () => { const frame = useCurrentFrame(); return <AbsoluteFill style={{background: 'radial-gradient(circle at 50% 42%, #493B2D 0%, #1B1814 36%, #080808 78%)', overflow: 'hidden'}}>{Array.from({length: 20}).map((_, i) => <div key={i} style={{position: 'absolute', left: random(`rr-x-${i}`) * 1080, top: random(`rr-y-${i}`) * 1920, width: 4 + random(`rr-z-${i}`) * 15, height: 4 + random(`rr-z-${i}`) * 15, borderRadius: 50, background: C.gold, filter: 'blur(3px)', opacity: .1 + .35 * Math.abs(Math.sin(frame * .035 + i))}} />)}</AbsoluteFill>; };

const Rings: React.FC = () => { const frame = useCurrentFrame(); const {fps} = useVideoConfig(); const p = spring({frame, fps, config: {damping: 13, stiffness: 70}}); return <div style={{position: 'relative', width: 330, height: 220, margin: '0 auto 80px', transform: `scale(${p})`}}><div style={{position: 'absolute', left: 38, top: 12, width: 190, height: 190, border: `15px solid ${C.gold}`, borderRadius: '50%', boxShadow: '0 0 35px rgba(213,179,106,.4)'}} /><div style={{position: 'absolute', right: 38, top: 12, width: 190, height: 190, border: `15px solid ${C.gold}`, borderRadius: '50%', boxShadow: '0 0 35px rgba(213,179,106,.4)'}} /><div style={{position: 'absolute', left: 146, top: -28, width: 42, height: 42, background: C.white, transform: 'rotate(45deg)', boxShadow: '0 0 35px white', clipPath: 'polygon(50% 0, 100% 38%, 78% 100%, 22% 100%, 0 38%)'}} /></div>; };

const Hero: React.FC<WeddingProps> = (props) => <AbsoluteFill style={{justifyContent: 'center', textAlign: 'center', padding: 110}}><Rings /><Rise delay={12} style={{fontFamily: sans, color: C.gold, fontSize: 26, letterSpacing: 12, textTransform: 'uppercase'}}>We are engaged</Rise><Rise delay={20} style={{fontFamily: serif, color: C.white, fontSize: 116, lineHeight: 1.05, marginTop: 45}}>{props.couple.partnerOne}<div style={{fontSize: 52, color: C.gold, fontStyle: 'italic', margin: 15}}>and</div>{props.couple.partnerTwo}</Rise><Rise delay={32} style={{fontFamily: sans, color: C.blush, fontSize: 36, marginTop: 55}}>{props.eventDate || 'Save the date'}<div style={{color: C.gold, marginTop: 14}}>{props.venue.name}{props.venue.city ? ` · ${props.venue.city}` : ''}</div></Rise></AbsoluteFill>;

const Card: React.FC<WeddingProps> = (props) => <AbsoluteFill style={{justifyContent: 'center', padding: 110}}><Rise style={{border: '1px solid rgba(213,179,106,.65)', padding: '105px 60px', textAlign: 'center', background: 'rgba(255,255,255,.025)', boxShadow: '0 0 90px rgba(213,179,106,.08)'}}><div style={{fontFamily: sans, fontSize: 24, letterSpacing: 10, color: C.gold, textTransform: 'uppercase'}}>The beginning of forever</div><div style={{fontFamily: serif, fontSize: 68, lineHeight: 1.35, color: C.blush, fontStyle: 'italic', marginTop: 55}}>{props.message || 'Join us as we celebrate a promise, a partnership, and a lifetime of love.'}</div></Rise></AbsoluteFill>;

const Portrait: React.FC<WeddingProps & {duration: number}> = (props) => { const frame = useCurrentFrame(); const src = props.photos?.[0]; return <AbsoluteFill style={{justifyContent: 'center', alignItems: 'center'}}>{src ? <div style={{width: 830, height: 1240, overflow: 'hidden', borderRadius: 420, border: `2px solid ${C.gold}`, boxShadow: '0 30px 100px rgba(0,0,0,.6)'}}><Img src={src} pauseWhenLoading style={{width: '100%', height: '100%', objectFit: 'cover', transform: `scale(${interpolate(frame, [0, props.duration], [1.1, 1.01])})`}} /></div> : <Rings />}</AbsoluteFill>; };

const Details: React.FC<WeddingProps> = (props) => <AbsoluteFill style={{justifyContent: 'center', padding: 120, textAlign: 'center'}}><Rise style={{fontFamily: serif, fontSize: 82, color: C.white}}>Celebrate With Us</Rise><div style={{height: 1, background: C.gold, margin: '60px 0'}} />{(props.schedule?.length ? props.schedule : [{name: 'Engagement', time: props.eventDate || 'Save the date'}]).slice(0, 3).map((item, i) => <Rise key={`${item.name}-${i}`} delay={i * 8} style={{fontFamily: serif, color: C.blush, fontSize: 58, margin: 25}}>{item.name}<div style={{fontFamily: sans, color: C.gold, fontSize: 29, letterSpacing: 3, marginTop: 9}}>{item.time}</div></Rise>)}<Rise delay={26} style={{fontFamily: sans, color: C.blush, fontSize: 31, marginTop: 55}}>{props.venue.name}{props.venue.city ? ` · ${props.venue.city}` : ''}</Rise></AbsoluteFill>;

export const RingReveal: React.FC<WeddingProps> = (props) => { const {durationInFrames, fps} = useVideoConfig(); const frame = useCurrentFrame(); const p = sectionPlan(durationInFrames); const volume = interpolate(frame, [0, fps, durationInFrames - fps, durationInFrames], [0, 1, 1, 0], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'}); return <AbsoluteFill>{props.musicUrl ? <Audio src={props.musicUrl} volume={volume} /> : null}<Background /><Sequence durationInFrames={p.intro}><SceneFade duration={p.intro}><Hero {...props} /></SceneFade></Sequence><Sequence from={p.intro} durationInFrames={p.message}><SceneFade duration={p.message}><Card {...props} /></SceneFade></Sequence><Sequence from={p.intro + p.message} durationInFrames={p.photos}><SceneFade duration={p.photos}><Portrait {...props} duration={p.photos} /></SceneFade></Sequence><Sequence from={p.intro + p.message + p.photos} durationInFrames={p.schedule}><SceneFade duration={p.schedule}><Details {...props} /></SceneFade></Sequence><Sequence from={durationInFrames - p.finale} durationInFrames={p.finale}><SceneFade duration={p.finale}><Hero {...props} /></SceneFade></Sequence></AbsoluteFill>; };
